### ISSUE TITLE
Feature request: Ability to pause a created game

### ISSUE THREAD

**Issue by tttppp** [zond/diplicity#90]
Originally posted by @bsweezy here: https://github.com/spamguy/dipl.io/issues/39

If I have created a game, it would be helpful to be able to pause the game. I haven't seen this functionality in other clients, but it would be useful. We got to the point where everyone wanted to take a break from the game but the phases kept proceeding relentlessly!

**Comment by zond** [comment]
I believe a voting function, or a possibility for every player to pause the
game once each might work?

**Comment by bsweezy** [comment]
Not necessarily the route you want to go, but PlayDiplomacy has some game modes that include an explicitly designated game master with privileges, possibly like pausing. They call it a "teaching" mode that is set when the game is created.  I haven't tried it.

**Comment by spamguy** [comment]
Voting would probably neutralise the feature, because if people are apathetic and don't vote (welcome to America!), people who really need time off won't get it despite lack of opposition. I think a limited amount of free passes per game/length of time should be fine, followed by (smaller than normal?) penalties to reliability.

**Comment by zond** [comment]
The voting could be constructed so that abstaining means approving?

On Jul 31, 2017 23:19, "spamguy" <notifications@github.com> wrote:

Voting would probably neutralise the feature, because if people are
apathetic and don't vote (welcome to America!), people who really need time
off won't get it despite lack of opposition. I think a limited amount of
free passes per game/length of time should be fine, followed by (smaller
than normal?) penalties to reliability.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/zond/diplicity/issues/90#issuecomment-319199662>, or mute
the thread

**Comment by zond** [comment]
I _think_ the same need is met by https://github.com/zond/diplicity/issues/166, but with a simpler solution.

@tttppp can we close this one then?

**Comment by tttppp** [comment]
Yep - I agree.  Grace periods is (are?) a better feature.
